# Generated by Django 2.2.6 on 2021-11-25 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0002_auto_20211125_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='service_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_app.services'),
        ),
    ]
