# Generated by Django 2.2.6 on 2021-11-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0004_auto_20211125_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.IntegerField(null=True),
        ),
    ]
