# Generated by Django 2.1 on 2021-11-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0006_auto_20211123_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='custumer_name',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Customer name'),
        ),
    ]
