# Generated by Django 3.0.7 on 2021-12-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0007_auto_20211208_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='generate_invoice',
            field=models.BooleanField(default=False),
        ),
    ]
