# Generated by Django 3.0.7 on 2021-12-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0008_invoice_generate_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Remarks'),
        ),
    ]
