# Generated by Django 3.0.7 on 2021-12-13 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0009_auto_20211213_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='remarks',
            new_name='remarks_expense',
        ),
    ]
