# Generated by Django 3.0.7 on 2021-12-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0012_auto_20211227_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='sale_number',
            field=models.CharField(blank=True, default='', max_length=120, null=True, unique=True, verbose_name='Customer Name'),
        ),
    ]
