# Generated by Django 3.2.9 on 2021-12-29 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0014_auto_20211229_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='expense_number',
        ),
    ]
