# Generated by Django 3.2.9 on 2021-12-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0015_remove_expense_expense_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(null=True, verbose_name='Travel Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sale_number',
            field=models.CharField(blank=True, default='', max_length=120, null=True, unique=True, verbose_name='PNR'),
        ),
    ]
