# Generated by Django 3.2.9 on 2022-01-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0017_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='date1',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='date2',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='date3',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='pending1',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Pending '),
        ),
        migrations.AddField(
            model_name='new',
            name='pending2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Pending '),
        ),
        migrations.AddField(
            model_name='new',
            name='pending3',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Pending '),
        ),
    ]
