# Generated by Django 3.2.9 on 2022-01-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0018_auto_20220107_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='date1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='date2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='date3',
            field=models.DateField(blank=True, null=True),
        ),
    ]
