# Generated by Django 3.2.9 on 2022-01-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0020_alter_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='date2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='date3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='received1',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Pending '),
        ),
        migrations.AddField(
            model_name='invoice',
            name='received2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Pending '),
        ),
        migrations.AddField(
            model_name='invoice',
            name='received3',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Pending '),
        ),
    ]
