# Generated by Django 3.2.9 on 2022-01-31 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0021_auto_20220109_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='custumer_name',
            field=models.CharField(blank=True, default='null', max_length=120, null=True, verbose_name='Customer Name'),
        ),
    ]
