# Generated by Django 3.2.9 on 2022-02-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0022_alter_invoice_custumer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='custumer_name',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Customer Name'),
        ),
    ]
