# Generated by Django 3.0.7 on 2022-02-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0022_auto_20220201_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='custumer_name',
            field=models.CharField(blank=True, default='null', max_length=120, null=True, verbose_name='Customer Name'),
        ),
    ]
