# Generated by Django 2.1 on 2021-11-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0023_auto_20211124_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='custumer_name',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
