# Generated by Django 3.0.7 on 2022-02-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0024_auto_20220201_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Service name'),
        ),
    ]
