# Generated by Django 2.1 on 2021-11-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0024_auto_20211124_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='custumer_name',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Customer Name'),
        ),
    ]
