# Generated by Django 3.0.7 on 2022-02-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0024_auto_20220203_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='manual_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Issue Date'),
        ),
    ]
