# Generated by Django 3.0.7 on 2022-02-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0025_auto_20220201_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='custumer_name',
            field=models.CharField(blank=True, default='null', max_length=120, null=True, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_name',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Service name'),
        ),
    ]
