# Generated by Django 3.0.7 on 2022-02-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0025_invoice_manual_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Travel Date'),
        ),
    ]
