# Generated by Django 2.1 on 2021-11-23 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0025_invoice_custumer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='service_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_app.services'),
        ),
    ]
