# Generated by Django 3.0.7 on 2022-02-09 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0026_auto_20220208_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='geeks_field',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
    ]
