# Generated by Django 3.0.7 on 2022-02-09 06:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0027_invoice_geeks_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='geeks_field',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
