# Generated by Django 3.0.7 on 2022-02-09 06:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0028_auto_20220209_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='geeks_field',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='geek'),
        ),
    ]
