# Generated by Django 3.0.7 on 2022-02-23 05:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0029_auto_20220209_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='Destination1',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Destination'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='Destination2',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Destination'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='Destination3',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Destination'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='Travel_date1',
            field=models.DateField(blank=True, null=True, verbose_name='Travel Date'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='Travel_date2',
            field=models.DateField(blank=True, null=True, verbose_name='Travel Date'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='Travel_date3',
            field=models.DateField(blank=True, null=True, verbose_name='Travel Date'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='purchase1',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Passenger Name'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='purchase2',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Passenger Name'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='purchase3',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Passenger Name'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='travel_time1',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='geek'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='travel_time2',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='geek'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='travel_time3',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='geek'),
        ),
    ]
