# Generated by Django 3.0.7 on 2022-02-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0030_auto_20220223_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='purchase1',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Passenger'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='purchase2',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Passenger'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='purchase3',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Passenger'),
        ),
    ]
