# Generated by Django 3.2.9 on 2021-12-23 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Expense name')),
                ('expense_number', models.IntegerField(blank=True, default=0, null=True, unique=True, verbose_name='Expense Number ')),
                ('amount', models.IntegerField(blank=True, default=0, null=True, verbose_name='Expense Amount ')),
                ('travel_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('date', models.DateField(null=True)),
                ('remarks_expense', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Remarks')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_number', models.IntegerField(blank=True, default=0, unique=True, verbose_name='Service Number')),
                ('service_name', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Service name')),
                ('remarks', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Remarks')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_number', models.IntegerField(blank=True, default=0, unique=True, verbose_name='Sale Number')),
                ('custumer_name', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Customer Name')),
                ('purchase', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Purchase Name')),
                ('purchase_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Purchase Price')),
                ('sale_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Sale Price')),
                ('date', models.DateField(null=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Remarks')),
                ('profit', models.IntegerField(blank=True, default=0, null=True, verbose_name='Profit')),
                ('Destination', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Destination')),
                ('travel_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('received', models.IntegerField(blank=True, default=0, null=True, verbose_name='Received')),
                ('pending', models.IntegerField(blank=True, default=0, null=True, verbose_name='Pending ')),
                ('phone', models.IntegerField(blank=True, default='0', null=True, verbose_name='Phone number')),
                ('generate_invoice', models.BooleanField(default=False)),
                ('service_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='apache_test.services')),
            ],
        ),
    ]
